version: "3.8"
services:
  data-transfer:
    image: ghcr.io/ninanor/WP1-data-transfer/tabmon-data-transfer
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 60s
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcs_key
      RCLONE_CONFIG: /run/secrets/tabmon_rclone
    secrets:
      - tabmon_rclone
      - gcs_key
secrets:
  tabmon_rclone:
    external: true
  gcs_key:
    external: true
