version: "3.8"
services:
  data-transfer:
    image: ghcr.io/ninanor/WP1-data-transfer/ghcr.io/ninanor/tabmon-data-transfer
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 60s
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcs_key.json
      RCLONE_CONFIG: /run/secrets/rclone.conf
    secrets:
      - source: tabmon_rclone.conf
        target: rclone.conf
      - source: gcs_key.json
        # No need for target // default to source if target not specified
secrets:
  tabmon_rclone.conf:
    external: true
  gcs_key.json:
    external: true
